# Generated by Django 4.1.1 on 2022-09-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'Bands'},
        ),
        migrations.RenameField(
            model_name='bandmember',
            old_name='band_member_name',
            new_name='name',
        ),
    ]
