# Generated by Django 4.1.1 on 2022-09-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_band_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bandmember',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'BandMembers'},
        ),
        migrations.AlterField(
            model_name='guitar',
            name='name',
            field=models.CharField(choices=[(1, 'ACOUSTIC'), (2, 'ELECTRIC'), (3, 'BASS')], max_length=40),
        ),
    ]
