# Generated by Django 4.1.1 on 2022-09-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bandmember_options_alter_guitar_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='name',
            field=models.CharField(choices=[('Acoustic', 'Acoustic'), ('Electric', 'Electric'), ('Bass', 'Bass')], max_length=40),
        ),
    ]
